### ISSUE TITLE
Barometric Sensor Not Working after update to MB122

### ISSUE THREAD

**Issue by neiloakley** [moshe-braner/SoftRF#15]
![IMG_6262](https://github.com/moshe-braner/SoftRF/assets/33990870/231480a7-d536-449b-8211-f1cd7796d51c)
![IMG_6261](https://github.com/moshe-braner/SoftRF/assets/33990870/09a4aa4c-bb33-427e-b267-2da3af067ddc)

--------------------

## Hardware

- [ ]   Standalone
- [X]   Badge
- [ ]   Prime Mark II
- [ ]   Dongle
- [ ]   Bracelet
- [ ]   Uni
- [ ]   Mini
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

## Describe the bug
Since updating to MB122 (in order to work with 2024 FLARM changes), the unit no longer sees the baro sensor. Was working fine previously as is the version that came with baro sensor built in (not added later). 

## To Reproduce
Unsure. Issue is visible from power on. 

## Expected behavior
Baro sensor should be seen by the software, and the baro page visible ti display pressure in mb.

**Comment by moshe-braner** [comment]
Which version of SoftRF was the baro sensor last working in?

**Comment by moshe-braner** [comment]
Fixed in MB123.  If still any issues let me know.  Thanks.
