### ISSUE TITLE
Broken Documentation Link

### ISSUE THREAD

**Issue by Exadios** [moshe-braner/SoftRF#16]
## General 

- Use this form to report bugs in released SoftRF firmware, hardware and web pages ;
- Prior to asking a question, look into Closed issues ;
- Thank you!

Recommended:
- screenshot or photo width - from 600 to 800 pixels ;
- aspect ratio - 4:3, 3:4, 16:9 or 9:16.
- substitute 'space' by 'x' character to mark a hardware checkbox

--------------------

## Hardware

- [ ]   Standalone
- [ ]   Badge
- [x]   Prime Mark II
- [ ]   Dongle
- [ ]   Bracelet
- [ ]   Uni
- [ ]   Mini
- [ ]   SkyView EZ
- [ ]   Raspberry Edition
- [ ]   UAV
- [ ]   UAT978 module
- [ ]   Flight Recorder

< photo of your hardware > (if relevant)

## Firmware version

<  screenshot of WebUI and/or SoftRF Tool status page > (if relevant)

## Firmware settings

<  screenshot of WebUI and/or SoftRF Tool settings page > (if relevant)

## Describe the bug

In file software/firmware/source/README.md the link [these official instructions](https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md) is broken.

## To Reproduce

In a Web browser go to https://github.com/moshe-braner/SoftRF/blob/master/software/firmware/source/README.md and select the link under the heading "ESP32"

## Expected behavior

Access to the installation instructions.

**Comment by moshe-braner** [comment]
Thanks for reporting!  I will fix this next time I post a new version.  Meanwhile, here is an updated link:  https://github.com/espressif/arduino-esp32/blob/master/docs/en/installing.rst
And note that I use the ESP32 Core version 2.0.3 - later versions make binaries that are too large to fit in the flash while allowing for wifi updates (which requires room for two versions in the flash at once).

**Comment by VirusPilot** [comment]
> Thanks for reporting! I will fix this next time I post a new version. Meanwhile, here is an updated link: https://github.com/espressif/arduino-esp32/blob/master/docs/en/installing.rst And note that I use the ESP32 Core version 2.0.3 - later versions make binaries that are too large to fit in the flash while allowing for wifi updates (which requires room for two versions in the flash at once).

Thank you for this inside - I never thought about how the WiFi update works, can you briefly explain it? Is it flashed to the ota_1 partition? If so, what follows next?

**Comment by moshe-braner** [comment]
The partition used for SoftRF, called "minimal SPIFFS", leaves only about 200 KB for the SPIFFS files area.  The rest of the 4MB flash is divided into two halves.  The current firmware sits in one half.  The update loads the new firmware into the other half.  Then it does a check to make sure it was not corrupted.  Then I think it copies it to the first half - I am not sure about that, but there is a delay that seems to be for that.  (I don't know why it doesn't simply swap the roles of the two halves.)  Then it reboots.  The current binary uses about 90% of the space available that way.

**Comment by Exadios** [comment]
> Thanks for reporting! I will fix this next time I post a new version. Meanwhile, here is an updated link: https://github.com/espressif/arduino-esp32/blob/master/docs/en/installing.rst And note that I use the ESP32 Core version 2.0.3 - later versions make binaries that are too large to fit in the flash while allowing for wifi updates (which requires room for two versions in the flash at once).

Thanks for the information. That explains why you have not been tracking the current ESP32 libraries.

I'm not familiar with the ESP32 hardware or the Arduino development environment but I cannot see an easy way to get an non current Core version. Trying esp32-arduino-lib-builder to give me v2.0.3.

**Comment by moshe-braner** [comment]
In that brief Installing guide, see the image after "Open Boards Manager from Tools > Board menu and install esp32 platform" - there is a drop-down arrow next to the latest version (2.0.0 in the image), you can select an older version.

**Comment by Exadios** [comment]
> In that brief Installing guide, see the image after "Open Boards Manager from Tools > Board menu and install esp32 platform" - there is a drop-down arrow next to the latest version (2.0.0 in the image), you can select an older version.

Thanks for the heads up. How can I have missed that.

**Comment by moshe-braner** [comment]
fixed the link in MB138
