### ISSUE TITLE
line endings in source code

### ISSUE THREAD

**Issue by moshe-braner** [moshe-braner/SoftRF#5]
My compilation setup is within Linux (using the Arduino IDE).  Thought the line endings in source files should be Linux-standard (lf only).  Turns out that Linar's source files have Windows line endings (cr-lf).  The commits for the first version ended up replacing every line in every touched file, just due to the line endings.  Thus github's "diff" feature won't show you exactly what I changed in the source.  Sorry for that.

I fixed the line endings in the source files to fit Linar's for my second version.  Github still won't show my changes, but you can run "diff" locally on your machine comparing my source files with Linar's (after you download both).

Tip: On Ubuntu 20.04 the default text editor silently preserves the line endings and you can't see what they are.  On Windows, use the text editor "Notepad2".  It is small, fast, free, will tell you what the line endings are, and you can easily change them.  Or use Wordpad, it is smart enough to read files with any type line end, and if you save changes it silently converts to the Windows line ends.

Rant: I've been fighting this line-ending nonsense for 40 years and it's a huge waste of time.  Why oh why isn't github's diff as smart as Wordpad?

**Comment by rvt** [comment]
You can tell git how to deal with lineendings : https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by moshe-braner** [comment]
Maybe this is relevant?

https://devzone.nordicsemi.com/f/nordic-q-a/39088/nrf52840-dongle-is-serial-port-library-via-usb-possible
"The nRF52840 DK has a programming chip ... uses the pins 6 and 8. If
you use any other pins than these, you will see that you can't see the
UART communication through the micro USB port."

I see this in nRF52.h:
#define SOC_GPIO_PIN_CONS_RX  _PINNUM(0, 8) // P0.08
#define SOC_GPIO_PIN_CONS_TX  _PINNUM(0, 6) // P0.06

and in nRF52.cpp:
#if defined(USE_TINYUSB)
  Serial1.setPins(SOC_GPIO_PIN_CONS_RX, SOC_GPIO_PIN_CONS_TX);
  Serial1.begin(SERIAL_OUT_BR, SERIAL_OUT_BITS);
#endif
